# Generated by Django 2.0.5 on 2018-06-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsecWorkStatus', '0002_auto_20180603_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
