# Generated by Django 2.0.5 on 2018-06-04 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gsecWorkStatus', '0005_auto_20180604_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('agendaCategory', models.CharField(max_length=1500)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('Completed', 'COMPLETED'), ('ONGOING-LONG-TERM', 'Onging-Long-Term'), ('Ongoing-Short-term', 'ONGOING-SHORT-TERM'), ('Not-Started', 'NOT_STARTED'), ('Broken', 'BROKEN'), ('Not-Evaluated', 'NOT-EVALUATED'), ('Not-Evaluated-Subjective', 'NOT-EVALUATED-SUBJECTIVE')], default='Select', max_length=100)),
                ('representativeComments', models.CharField(blank=True, max_length=1000)),
                ('currentStatus', models.CharField(blank=True, max_length=1000)),
                ('unapprovedComment', models.CharField(blank=True, max_length=1000)),
                ('unapprovedStatus', models.CharField(blank=True, max_length=1000)),
                ('approved', models.IntegerField(default=0)),
                ('verifiedBy', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='post_description',
            field=models.CharField(max_length=255),
        ),
    ]
