# Generated by Django 2.0.5 on 2018-06-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsecWorkStatus', '0006_auto_20180604_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='verifiedBy',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
