# Generated by Django 2.0.5 on 2018-06-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsecWorkStatus', '0007_auto_20180606_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='verifiedBy',
            new_name='StatusCategory',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='approved',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
