# Generated by Django 2.0.5 on 2018-06-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsecWorkStatus', '0008_auto_20180606_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('Completed', 'COMPLETED'), ('ONGOING-LONG-TERM', 'Ongoing-Long-Term'), ('Ongoing-Short-term', 'ONGOING-SHORT-TERM'), ('Not-Started', 'NOT_STARTED'), ('Broken', 'BROKEN'), ('Not-Evaluated', 'NOT-EVALUATED'), ('Not-Evaluated-Subjective', 'NOT-EVALUATED-SUBJECTIVE')], default='Select', max_length=100),
        ),
    ]
