# Generated by Django 2.0.5 on 2018-06-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsecWorkStatus', '0010_auto_20180606_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='approved',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
