# Generated by Django 2.0.5 on 2018-06-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsecWorkStatus', '0013_auto_20180606_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
