# Generated by Django 2.0.5 on 2018-06-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsecWorkStatus', '0014_auto_20180620_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='pdf',
        ),
    ]
