# Generated by Django 2.0.3 on 2020-01-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsecWorkStatus', '0016_userprofileinfo_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('AgendaCategory', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=1000)),
                ('Status', models.CharField(max_length=250)),
                ('Comment', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'agenda1',
            },
        ),
    ]
