# Generated by Django 2.0.3 on 2020-01-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsecWorkStatus', '0017_agenda1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda1',
        ),
    ]
