# Generated by Django 2.0.3 on 2020-01-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsecWorkStatus', '0018_delete_agenda1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='unapprovedStatus',
            field=models.CharField(blank=True, choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], max_length=1000),
        ),
    ]
