# Generated by Django 2.0.3 on 2020-01-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsecWorkStatus', '0019_auto_20200108_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='unapprovedStatus',
            field=models.CharField(choices=[('Completed', 'COMPLETED'), ('Ongoing-Long-Term', 'ONGOING-LONG-TERM'), ('Ongoing-Short-Term', 'ONGOING-SHORT-TERM'), ('Not-Started', 'NOT_STARTED'), ('Broken', 'BROKEN'), ('Not-Evaluated', 'NOT-EVALUATED'), ('Not-Evaluated-Subjective', 'NOT-EVALUATED-SUBJECTIVE')], default='Select', max_length=100),
        ),
    ]
